use_frameworks!

platform :ios, '8.0'

target 'ZMKHUserUploadPictureTool_Example' do
  pod 'ZMKHUserUploadPictureTool', :path => '../'

  target 'ZMKHUserUploadPictureTool_Tests' do
    inherit! :search_paths

    
  end
end
